Extracting geo-data from poc-message
Schrolli91/BOSWatch pull request #405
Opened 2019-09-05 06:26 UTC by flothi

instead of checking for locations in a specific plugin, a central approach is done here; at the moment, a regex containing coordinates is to be found in the poc-text. The coordinates are parsed and afterwards stored into data as lon/lat.

2019-09-06 18:37 UTC, Schrolli91 requested changes

2019-09-06 18:37 UTC, Schrolli91 commented on CHANGELOG.md
> +- POC-Decoder: Im POC-Text wird nach einem RegEx, welcher Koordinaten enthält, gesucht. Werden diese gefunden, so stehen zwei neu befüllte Data-Felder Lon bzw Lat zur Verfügung.
Der Eintrag sollte in den Block eins tiefer, welcher noch undatiert ist,

2019-09-06 18:37 UTC, Schrolli91 commented on config/config.template.ini
> +geo_format = #C(\d{2})(\d{5}),(\d{2})(\d{5})#
Sollte man hier ein Flag zum an-/ausschalten implementieren?

2019-09-07 11:39 UTC, flothi commented on config/config.template.ini
> +geo_format = #C(\d{2})(\d{5}),(\d{2})(\d{5})#
Hatte ich überlegt, perspektivisch wollte ich jedoch alle POC-Nachrichten über einen Geodecoder jagen.

2019-09-07 15:51 UTC, Schrolli91 requested changes

2019-09-07 15:51 UTC, Schrolli91 commented on CHANGELOG.md
> +- POC-Decoder: Im POC-Text wird nach einem RegEx, welcher Koordinaten enthält, gesucht. Werden diese gefunden, so stehen zwei neu befüllte Data-Felder Lon bzw Lat zur Verfügung.
Ich meinte eigentlich, dass dieser Eintrag in den schon vorhandenen, undatierten Block eingefügt werden sollte. Der von dir erstelle Changelog-Block fällt damit komplett raus. Einen neuen Block erstelle ich immer erst zum Release einer neuen Version

2019-09-07 15:51 UTC, Schrolli91 commented on config/config.template.ini
> +geo_format = #C(\d{2})(\d{5}),(\d{2})(\d{5})#
Versteh ich jetzt nicht ganz.
Was ich meinte ist, ein Flag in der Config mit dem man das "Regex'en" der Geo-Daten komplett ausschalten kann.
Bzw. wie sieht das aktuell aus? Wenn keine Regex String angeben ist? Führt das zu einer Exception, oder ist das `has_Geo`-Flag dann sowieso false?

2019-09-07 20:13 UTC, flothi commented on CHANGELOG.md
> +- POC-Decoder: Im POC-Text wird nach einem RegEx, welcher Koordinaten enthält, gesucht. Werden diese gefunden, so stehen zwei neu befüllte Data-Felder Lon bzw Lat zur Verfügung.
Jetzt verstanden, erledigt

2019-09-07 20:57 UTC, flothi commented
@Schrolli91 Exception-Handling hab ich jetzt eingebaut, danke für den Hinweis!

2019-09-08 16:15 UTC, Schrolli91 commented on includes/decoders/poc.py
> +                    			m = re.search(globalVars.config.get("POC","geo_format"),poc_text)
Was passiert hier, wenn `geo_format`, also der RegEX Stiring NICHT gesetzt ist?
Kann hier eine Exception fliegen?

2019-09-10 22:12 UTC, flothi commented on includes/decoders/poc.py
> +                    			m = re.search(globalVars.config.get("POC","geo_format"),poc_text)
Kann sie, wird allerdings abgefangen und es wird so gehandelt, als ob keine Auswertung stattgefunden hat; das data-Feld "has_geo" wird auf false gesetzt.

2019-09-11 14:47 UTC, Schrolli91 commented on includes/decoders/poc.py
> +                    			m = re.search(globalVars.config.get("POC","geo_format"),poc_text)
Dann wäre es besser vor der Abfrage zu prüfen ob ein Regex vorhanden ist. Oder ein Enable Flag aus der Config lesen.
Eine Exception gewillt zu schmeißen ist nicht schön. Und nicht jeder wird diese Funktion nutzen wollen/können.

2019-09-11 21:57 UTC, flothi commented on includes/decoders/poc.py
> +                    			m = re.search(globalVars.config.get("POC","geo_format"),poc_text)
Alles klar, ich setze dann noch ein Flag ein - perspektivisch kommt ja auch noch was mehr dazu (Geodecode mit Straße/PLZ), dann passt das

2019-09-20 06:21 UTC, Schrolli91 commented on includes/decoders/poc.py
> +                    			m = re.search(globalVars.config.get("POC","geo_format"),poc_text)
Gibts hier schon Neuigkeiten?

2019-09-20 06:31 UTC, flothi commented on includes/decoders/poc.py
> +                    			m = re.search(globalVars.config.get("POC","geo_format"),poc_text)
Ist in Arbeit

2019-09-20 06:38 UTC, Schrolli91 commented on includes/decoders/poc.py
> +                    			m = re.search(globalVars.config.get("POC","geo_format"),poc_text)
Alles klar, super!
Wollte da jetzt auf keine Hektik rein bringen - war rein Interessehalber.
Danke dir.

2019-09-20 22:36 UTC, flothi commented
So, jetzt auch in der Variante mit Switch in der Config.

2019-09-21 12:15 UTC, Schrolli91 requested changes

2019-09-21 12:15 UTC, Schrolli91 commented on includes/decoders/poc.py
> +                		poc_text = decoded.split('Alpha:   ')[1].strip().replace('<NUL><NUL>','').replace('<NUL>','').repl$
Was ist den hier passiert? Siehe Zeilenende!
Solche Stellen gibt es mehrmals.

2019-09-21 21:51 UTC, flothi commented on includes/decoders/poc.py
> +                		poc_text = decoded.split('Alpha:   ')[1].strip().replace('<NUL><NUL>','').replace('<NUL>','').repl$
Ich habe zwei Stellen gefunden und gefixt; erklären kann ichs beim besten Willen nicht...

2019-09-21 22:13 UTC, Schrolli91 approved these changes

2019-09-21 22:16 UTC, merged