Sound-Settings für Pushover
Schrolli91/BOSWatch pull request #418
Opened 2019-10-17 12:48 UTC by grosj

2019-10-17 12:57 UTC, Schrolli91 commented
LGTM

2019-10-17 12:57 UTC, Schrolli91 approved these changes

2019-10-17 13:20 UTC, Schrolli91 requested changes
Fehlt da nicht noch die config?

2019-10-17 13:22 UTC, grosj commented
> Fehlt da nicht noch die config?

Upps.... jepp... füge ich noch ein!

2019-10-17 13:41 UTC, Schrolli91 commented
Jetzt sieht das gut aus ;-)
Lokal getestet - gehe ich von aus?

2019-10-17 13:41 UTC, Schrolli91 approved these changes

2019-10-17 13:43 UTC, grosj commented
> Lokal getestet - gehe ich von aus?

Aber natürlich ;-)

2019-10-17 13:57 UTC, merged

2019-10-17 13:58 UTC, Schrolli91 commented
Dann vielen Dank für deine Mithilfe

2019-10-17 20:01 UTC, grosj commented
> Dann vielen Dank für deine Mithilfe

Gerne. Und für MQTT hätte ich auch schon ein Plugin parat. ;-)

2019-10-18 05:44 UTC, Schrolli91 commented
Wenn du soweit bist gerne PR stellen ;-)

2019-10-18 06:15 UTC, grosj commented
> Wenn du soweit bist gerne PR stellen ;-)

Bei mir läuft das MQTT-Plugin bereits. Und ohne Fehler. 
Allerdings sind hierfür ein paar zusätzliche Libs notwendig, die dann in das Install-Skript mit aufgenommen werden müssen. Zusätzlichen müssen diese Lips müssen dann mit pip bzw. pip3 für Python bekannt (?) gemacht werden.
Und da hakt es bei mir ein wenig.

2019-10-18 06:49 UTC, Schrolli91 commented
Siehe hier: https://github.com/Schrolli91/BOSWatch/blob/ca26f1dc9a71d166c3dc9612924781511fb97ae6/plugins/Telegram/Telegram.py#L7

Einfach die benötigte Lib namentlich vermerken, um eine Installation muss sich der User selbst kümmern. Wenn das Install Skript zu allen Plugins, alle deps gelich mit installiert, hat man ja 95% overhead dabei.

2019-10-18 07:26 UTC, grosj commented
> Siehe hier:
> 
> https://github.com/Schrolli91/BOSWatch/blob/ca26f1dc9a71d166c3dc9612924781511fb97ae6/plugins/Telegram/Telegram.py#L7
> 
> Einfach die benötigte Lib namentlich vermerken, um eine Installation muss sich der User selbst kümmern. Wenn das Install Skript zu allen Plugins, alle deps gelich mit installiert, hat man ja 95% overhead dabei.
> 
> Der MySQL Connector ist das einzige was mit installiert wird - und das ist eher eine Altlast

Ach so, ok, dann werde ich dies so vermerken. Der PR kommt dann die Tage.
Für MySQL fand ich das allerdings ziemlich praktisch. ;-)

2019-10-18 08:07 UTC, Schrolli91 commented
Für BW3 ist angedacht eine Art automatischen Deps-Installer einzubauen.
Aber so weit war ich bei BW2 damals noch nicht.
Das Script sollte eigentlich nur POCSAG -> SQL machen , siehste ja, wo wir jetzt stehen :-D

2019-10-18 11:00 UTC, flothi commented
Vorschlag: Man könnte, wie bei mysql auch, eine Batchdatei hinzufügen, die dann die entsprechenden Pakete runterlädt. Aber das sollten wir dann im entsprechenden Issue/PR diskutieren.