Mqtt-Plugin
Schrolli91/BOSWatch pull request #419
Opened 2019-10-23 08:45 UTC by grosj

2019-10-23 08:49 UTC, grosj commented
Läuft bereits seit über einer Woche erfolgreich bei mir.

2019-10-23 09:18 UTC, Schrolli91 requested changes

2019-10-23 09:18 UTC, Schrolli91 commented on plugins/mqtt/mqtt.py
> +                return
Wieso return an dieser Stelle?

2019-10-23 09:18 UTC, Schrolli91 commented on plugins/mqtt/mqtt.py
> +                return
Wieso return an dieser Stelle?

2019-10-23 09:18 UTC, Schrolli91 commented on plugins/mqtt/mqtt.py
> +                client.connect(globalVars.config.get("mqtt", "broker_address"))
Vielleicht wäre es sinnvoll, den Port auch noch konfigurierbar zu machen? Was meinst du?

2019-10-23 09:55 UTC, grosj commented on plugins/mqtt/mqtt.py
> +                client.connect(globalVars.config.get("mqtt", "broker_address"))
Mhh... könnte man machen... Werd ich mal einbauen. Dann muss es allerdings bei mir nochmal probelaufen.

2019-10-23 09:56 UTC, flothi commented
Ich fände es super, wenn wir direkt die verschlüsselte Verbindung zum Broker anbieten würden. Sprich Zertifikat hinterlegen.

2019-10-23 10:01 UTC, grosj commented on plugins/mqtt/mqtt.py
> +                return
In der Zeile davor stand vorher ein Logging, dass dieser Typ nicht supported wird. Beim Einfügen der Config-Abfrage habe ich dann vergessen das return zu entfernen. Ist nachgebessert.

2019-10-23 10:01 UTC, grosj commented on plugins/mqtt/mqtt.py
> +                return
In der Zeile davor stand vorher ein Logging, dass dieser Typ nicht supported wird. Beim Einfügen der Config-Abfrage habe ich dann vergessen das return zu entfernen. Ist nachgebessert.

2019-11-04 15:35 UTC, grosj commented
Hab mal ein paar Konfigurationsmöglichkeiten hinzugefügt.
Läuft bei mir bisher einwandfrei... Allerdings habe ich verschlüsselte Verbindung inkl. der Zertifikate nicht getestet.

2019-11-04 18:24 UTC, Schrolli91 commented
Ich versuch die Woche mal genauer drüber zu schauen - bin aktuell etwas eingespannt.
Wenn du magst, kannst du ja mal versuchen über das BWCC den ein oder anderen zu einem Test zu motivieren :-D

2019-11-07 08:16 UTC, grosj commented
> Ich versuch die Woche mal genauer drüber zu schauen - bin aktuell etwas eingespannt.
> Wenn du magst, kannst du ja mal versuchen über das BWCC den ein oder anderen zu einem Test zu motivieren :-D

Jepp, alles gut...

2020-03-27 12:23 UTC, closed without merging

2020-03-27 20:00 UTC, Schrolli91 commented
@grosj gabs nen Grund für die Löschung?

2020-03-29 12:37 UTC, grosj commented
Ich hab einfach mal aufgeräumt. Hatte gedacht, dass es bereits im development-Branch drin ist. Da war ich wohl zu voreilig.