Update install.sh
Schrolli91/BOSWatch pull request #452
Opened 2020-05-02 15:42 UTC by lgremme

Bei einer Neuinstallation kann die MySQL-Datenbank nicht angesprochen werden. Ursache liegt in der veralteten mysql-connector-python. Diese wurde ersetzt. #445 

Skript-Variable: boswatch_install_path hinzugefügt und kopiert später die Inhalten nach $boswatchpath/install. Es wird das GIT-Verzeichnis direkt nach /opt/boswatch geklont und dort ein Unterordner am Ende für die Logs erstellt.

2020-05-04 13:26 UTC, Schrolli91 commented
> Skript-Variable: boswatch_install_path hinzugefügt und kopiert später die Inhalten nach $boswatchpath/install. Es wird das GIT-Verzeichnis direkt nach /opt/boswatch geklont und dort ein Unterordner am Ende für die Logs erstellt.

Verstehe den Grund nicht ganz

2020-05-04 13:29 UTC, Schrolli91 requested changes

2020-05-04 13:29 UTC, Schrolli91 commented on install.sh
> +    exitcodefunction $? git-clone BOSWatch-beta ;;
Am besten direkt rausschmeißen - den gibt es nicht mehr

2020-05-04 15:29 UTC, lgremme commented on install.sh
> +    exitcodefunction $? git-clone BOSWatch-beta ;;
Ist entfernt

2020-05-04 15:34 UTC, lgremme commented
Es besteht nicht die Möglichkeit, die Install-Datei direkt (ursprünglich) nach /opt/boswatch/install/setup_log.txt zu schreiben. "git clone boswatch . >>..." schlägt fehl, wenn dort ein Unterordner existiert. Später kann das Update einfach über git pull erfolgen. Es gibt diverse Möglichkeiten, später das .git-Verzeichnis mit zu kopieren, allerdings sehr unschön.

Später wird das nach log/install/setup_log.txt verschoben und der temporäre Ordner entfernt.

2020-05-05 06:57 UTC, Schrolli91 commented
So ganz verstehe ich das noch nicht :-D
Was hat denn da vorher nicht funktioniert und wurde damit jetzt gefixt?
Mir war gar nicht bewusst dass hier noch ein Fehler im Installer besteht.

2020-05-05 11:12 UTC, lgremme commented
Vorher konnte unter /opt/boswatch das lokale GIT-Repo nicht genutzt werden. Es sind die Dateien aus einem Unterordner zurück in den Wunschordner kopiert worden.

(alt):
- /opt/boswatch/install
- /opt/boswatch/BOSWatch (klone des Repos und später nach boswatch in den übergeordneten Ordner verschoben)

(neu):
- /opt/boswatch (Git clone direkt in den Ordner, alle Commits aufrufbar; Schwierigkeit: Ordner muss leer sein für dein git clone)
- /opt/boswatch_install (wird als temporäres Verzeichnis genutzt, war vorher /opt/boswatch/install)

Im alten Skript ist der Ordner /opt/boswatch/BOSWatch/.git nicht mit kopiert worden. Somit waren die Commits auf dem Repo nicht mehr nachzuvollziehen, auf welchem Stand die Installation ist. Gleichzeitig wird das Update einfacher für die nächsten Versionen, da nur "git pull" eingegeben werden muss.

Kurz und knapp:
Fehler: .git aus dem Klone-Ordner wird nicht kopiert. Folge davon, kein lokales git-Repo mit den Commits zur Verfügung.

2020-05-05 13:24 UTC, Schrolli91 approved these changes

2020-05-05 13:24 UTC, Schrolli91 commented
Changelog bitte noch kurz anpassen

2020-05-05 15:54 UTC, Schrolli91 approved these changes

2020-05-05 15:54 UTC, merged