Added Plugin MQTT
Schrolli91/BOSWatch pull request #498
Opened 2020-12-18 14:16 UTC by mrduckspace

Plugin für die Übermittlung von POSAC an einem MQTT-Broker

2020-12-18 18:14 UTC, Schrolli91 commented
Vielen Dank für deinen Beitrag - ich versuch am Wochenende ein Review zu machen :-)

2020-12-18 18:22 UTC, mrduckspace commented
Hey,
Immer gerne, finde deine Arbeit sehr gut. Falls du Mal Hilfe brauchst, melde dich gerne

Ja hab ich letzte Mal auch gemacht, hab es aber heute leider vergessen :D

2020-12-22 10:26 UTC, Schrolli91 approved these changes
LGTM

Hättest du Lust, FMS und ZVEI noch zu implementieren?
Falls nicht, würde ich es im aktuellen Stand mergen

2020-12-22 11:15 UTC, mrduckspace commented
Kann ich wohl machen, habe aber ehrlich gesagt keine Ahnung von FMS und ZVEI. Würde dann einfach die Wildcards (die in der Config unten stehen) als JSON per MQTT übergeben oder? @Schrolli91 

wird aber wahrscheinlich erst im Laufe der Woche was

2020-12-22 12:06 UTC, Schrolli91 commented
Ja genau, daran dachte ich. Einfach die Felder - wie mein POCSAG auch - in ein JSON packen und versenden.
Super Danke :-)

2020-12-22 12:35 UTC, mrduckspace commented
hab es doch jetzt schon geschafft :-) hoffe es passt so :P

2020-12-22 20:33 UTC, Schrolli91 requested changes

2020-12-22 20:33 UTC, Schrolli91 commented on config/config.template.ini
> +topic = alarm/posac
das passt jetzt als Beispiel nicht mehr ganz, da ja alle implementiert sind.
Besser wäre zB `alarm/data`

2020-12-22 21:10 UTC, mrduckspace commented
hab ich vorhin beim Ändern vergessen, ist geändert.

2020-12-24 07:32 UTC, Schrolli91 approved these changes
LGTM

2020-12-27 11:51 UTC, nobbie2009 approved these changes

2020-12-30 08:01 UTC, Schrolli91 requested changes

2020-12-30 08:01 UTC, Schrolli91 commented on CHANGELOG.md
> +- MQTT: Plugin für Übermittlung von POSAC an einen MQTT-Broker [#498](
Mir ist gerade noch aufgefallen, dass im Changelog nur POC steht.
Jetzt sind ja alle Telegramme unterstützt.

2020-12-30 08:02 UTC, Schrolli91 commented on CHANGELOG.md
> +- MQTT: Plugin für Übermittlung von POSAC an einen MQTT-Broker [#498](
Außerdem bitte an die Changelog Sprache (englisch) halten

2021-01-07 11:09 UTC, Schrolli91 approved these changes

2021-01-07 11:09 UTC, merged

2021-01-07 18:49 UTC, mrduckspace commented
hey danke @Schrolli91 ;) der Changelog ist bei mir untergegangen

2021-01-07 19:24 UTC, Schrolli91 commented
Kein Problem ;-) Hatte heut mal eben die zeit gefunden ;-)