Koordinaten für POC Texte hinterlegen
Schrolli91/BOSWatch pull request #510
Opened 2021-01-26 10:58 UTC by MarSch1

Hi, ich habe eine Möglichkeit eingebaut, wie man für bestimmte Einsatzstellen Koordinaten hinterlegen kann, mit denen dann die lat und lng Felder in der data-Struktur gefüllt werden.

Ausgangsproblem ist, dass v.a. bei Autobahnen oder außerörtliche Ortsangaben nachgelagerte Systeme (z.B. Divera) mit der Adressangabe im POC Text keine ordentliche Adressfindung hinkriegen. Wenn ich jetzt in der Konfiguration anhand von bestimmten Elementen in der data-Struktur Koordinaten hinterlege, werden diese dann in lat und lng übergeben zur Weiterverarbeitung in Plugins. Richtig sinnvoll ist das Feature natürlich nur in Zusammenhang mit Pull request ####, wenn ich dann tatsächlich Felder wie Ort, Ortsteil, Objekt etc. zur Verfügung habe.

Ich habe es so umgesetzt, dass erkannte GEO Angaben im POC Text Priorität haben (geo_enable, geo_format).

2021-01-26 11:22 UTC, Schrolli91 commented
Schau ich mir zum Wochenende an, vielen Dank schon mal für deinen Beitrag

2021-01-26 13:03 UTC, Schrolli91 requested changes
Ein paar Sachen sind mir auf die schnelle bereits aufgefallen

2021-01-26 13:03 UTC, Schrolli91 commented on config/config.template.ini
> +#[LocationCoordinates]
Bitte nicht die ganze Sektion aus kommentieren um das EIN/AUS zu erkennen, sondern wie zB beim multicastAlarm ein Flag zu nutzen `locationCoordinates = 0`

Ist zwar auch eine elegante Variante, soll sich aber konsistent zu den vorhanden Optionen verhalten.

2021-01-26 13:03 UTC, Schrolli91 commented on includes/locationCoordinates.py
> +		if globalVars.config.has_section("LocationCoordinates"):
Wie oben (Flag statt Sektion prüfen)

2021-01-26 13:03 UTC, Schrolli91 commented on boswatch.py
> +		from includes import locationCoordinates
Hier prüfen, ob Funktion angeschaltet ist und nur dann Importen - siehe descriptions oben drüber

2021-01-26 13:03 UTC, Schrolli91 commented on includes/locationCoordinates.py
> +		if globalVars.config.has_section("LocationCoordinates"):
Wobei das Flag eigentlich unnötig ist, weil die Funktion nicht gerufen werden sollte, wenn es nicht aktiv ist

2021-01-28 11:39 UTC, Schrolli91 requested changes
Sieht soweit gut aus, nur Kleinigkeiten

2021-01-28 11:39 UTC, Schrolli91 commented on CHANGELOG.md
> +- GPS-coordinates configuration based on POC message elements. [#510](https://github.com/Schrolli91/BOSWatch/pull/510)
Evtl. sollte man hier noch etwas deutlicher herausstellen, dass es sich um fix definierte Koordinaten handelt.
Und evtl. auch, dass dies auf Basis von Regex passiert.

2021-01-28 11:39 UTC, Schrolli91 commented on includes/locationCoordinates.py
> +					logging.info("Coordinates found!")
Bitte als Debug loggen. Falls noch irgendwo Info bitte auch gleich anpassen.

2021-01-28 20:25 UTC, MarSch1 commented
Sollte jetzt soweit passen denke ich.

2021-01-28 20:36 UTC, Schrolli91 approved these changes
LGTM - denke das passt so.
Werde da am Wochenende noch mal nen kurzen Blick drauf werden,
Und wenn mir nix mehr auffällt, würde ich mergen.
Danke schon mal dafür :-)

2021-02-02 09:35 UTC, merged